services:
  db:
    image: postgres:16
    container_name: edutrack_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edutrack_net

  web:
    build: .
    container_name: edutrack_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    networks:
      - edutrack_net

  nginx:
    image: nginx:alpine
    container_name: edutrack_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/static
      - media:/media
    depends_on:
      - web
    networks:
      - edutrack_net

volumes:
  postgres_data:
  static:
  media:

networks:
  edutrack_net:
